
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { navlinks, supportLinks } from "@/data/navlinks";
import { user } from "@/data/temperory-static.data";
import Config from "@/providers/Config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Config>
           <Navbar
            imgUrl="https://carboncell.io/assets/img/logo2.png"
            navLinks={navlinks}
            supportLinks={supportLinks}
          />
          {children}
        </Config>
      </body>
    </html>
  );
}
